travis:
  secure:
    BINSTAR_TOKEN: WuUEAL5AJiJny5PjZL78tHtyZqb9maco7IYjDwCtNM0PODVVNOECAtGLD6DU2KQzcfulhvWZXZpEFkTfAWgj5B74pn9tRaGptCbCLRf3oC4HeYvVeFSPtDUeHxtkh9Ie0oc2x5cQxWJQsapRcmqfHRIEH0rNgxE+IcMl8ph2w39FYnUx0pg/GzqWMhpKGeJhQBryUUxCI2VaTxH+HUVIgRl49ayJkmnabg/ezffGmRbfb/NSi0RWqHMWgxozJ5XRJZ7TfqjoDStIPrNF+66Sl2DvmP9OFxHDwumgxrtUbOG8Q2fmpf7pWK2sZeUct+GA84suu5xYPz39+2lozEZGdzQ+ytxBwJsCOqTwOIv15SQsMZ063a5sWCGW2eM1GCsL8A7bwQxHazuq2Ou66ARIqk8nydiHElFD6PrhjNHeJKIUFMj2a8LcQsypv6I2sA7BFsRLoXSq1uFy1H2BrIglieEoWe5M1WCjnwSjBEBXed/eShLe2gLjblUCZ6jDsSofXJQ/XkZvZ663oGF9a41YaL/C/FjG8KQ5qN7aZzhtshr+7rIbIvexjh9+gzxV6f6hA52wogai9XoRJO9UTXtOiOaZpEwwlIZOJVXZ1LlbE4A9kYQHNxmaQBa2uxTtpS4Gk/SfWBDDuyUWoryMgRveDvMflggme7UCDKi2q1GAakw=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
